# Generated by Django 5.2.6 on 2025-09-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('Run', 'Run'), ('Ride', 'Ride'), ('EBikeRide', 'EBikeRide'), ('Swim', 'Swim'), ('Walk', 'Walk'), ('Hike', 'Hike'), ('Workout', 'Workout'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
