# Generated by Django 5.2.6 on 2025-09-11 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activity_activity_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StravaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_user_id', models.BigIntegerField(unique=True)),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='activity',
            name='activities__strava__f1f438_idx',
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='strava_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('user', 'strava_id')},
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user', 'strava_id'], name='activities__user_id_ae2d9f_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user'], name='activities__user_id_a9ae64_idx'),
        ),
        migrations.AddField(
            model_name='stravaprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strava_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
